# Generated by Django 2.2.12 on 2021-06-26 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0008_auto_20210626_0703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='cover',
            field=models.FileField(default='SkillDrill/skilldrill/static/img/location/kathmandu.jpeg', upload_to='SkillDrill/skilldrill/static/img/location'),
        ),
    ]
