# Generated by Django 2.2.12 on 2021-06-26 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0010_remove_location_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='cover',
            field=models.FileField(default='img/location/kathmandu.jpeg', upload_to='skilldrill/static/img/location'),
        ),
    ]
