# Generated by Django 2.2.12 on 2021-06-26 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0011_location_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='cover',
        ),
    ]
