# Generated by Django 2.2.12 on 2021-06-27 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0012_remove_location_cover'),
    ]

    operations = [
        migrations.RenameField(
            model_name='services',
            old_name='service',
            new_name='title',
        ),
        migrations.AddField(
            model_name='services',
            name='description',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='time',
            field=models.IntegerField(null=True),
        ),
    ]
