# Generated by Django 2.2.12 on 2021-06-27 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0013_auto_20210627_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='category',
            field=models.CharField(choices=[('Painter', 'Painter'), ('Repair Appliances', 'Repair Appliances'), ('Home Spa', 'Home Spa'), ('Disinfecter', 'Disinfecter'), ('Photographer', 'Photographer'), ('Chemical Guy', 'Chemical Guy'), ('Trainer', 'Trainer'), ('Child Care', 'Child Care')], max_length=10, null=True),
        ),
    ]
