# Generated by Django 2.2.12 on 2021-06-27 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0014_services_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='category',
        ),
    ]
