# Generated by Django 2.2.13 on 2021-06-28 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0017_auto_20210627_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='category',
            field=models.CharField(choices=[('Painter', 'Painter'), ('Repair Appliances', 'Repair Appliances'), ('Home Spa', 'Home Spa'), ('Disinfecter', 'Disinfecter'), ('Photographer', 'Photographer'), ('Chemical Guy', 'Chemical Guy'), ('Trainer', 'Trainer'), ('Child Care', 'Child Care'), ('Beauty', 'Beauty')], max_length=30, null=True),
        ),
    ]
