# Generated by Django 2.2.12 on 2021-07-05 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0018_auto_20210628_1012'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('manager', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='services',
            old_name='manager',
            new_name='professional',
        ),
        migrations.RemoveField(
            model_name='services',
            name='category',
        ),
        migrations.AddField(
            model_name='services',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='categories', to='locations.Category'),
        ),
    ]
