# Generated by Django 2.2.12 on 2021-07-05 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0020_auto_20210705_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='location',
        ),
        migrations.AddField(
            model_name='category',
            name='location',
            field=models.ManyToManyField(blank=True, related_name='services', to='locations.Location'),
        ),
    ]
