# Generated by Django 2.2.12 on 2021-07-06 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0021_auto_20210705_1435'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='title',
            new_name='categoty',
        ),
        migrations.AlterField(
            model_name='category',
            name='location',
            field=models.ManyToManyField(blank=True, related_name='categories', to='locations.Location'),
        ),
        migrations.AlterField(
            model_name='services',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='locations.Category'),
        ),
    ]
