# Generated by Django 2.2.12 on 2021-07-06 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0022_auto_20210706_0744'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='categoty',
            new_name='category',
        ),
    ]
