# Generated by Django 2.2.12 on 2021-07-08 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0026_auto_20210708_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.Category'),
        ),
    ]
