# Generated by Django 2.2.12 on 2021-07-12 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0027_auto_20210708_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rel_cat', to='locations.Category'),
        ),
    ]
