# Generated by Django 2.2.12 on 2021-07-13 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0028_auto_20210712_0444'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='cover',
            field=models.FileField(default='img/location/kathmandu.jpeg', upload_to='skilldrill/static/img/location'),
        ),
    ]
