# Generated by Django 3.2.4 on 2021-07-14 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0028_auto_20210712_0444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='location',
            field=models.ManyToManyField(related_name='services', to='locations.Location'),
        ),
    ]
