# Generated by Django 3.2.4 on 2021-07-14 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0029_alter_services_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='cover',
            field=models.FileField(default='img/location/lalitpur.jpeg', upload_to='img/location'),
        ),
    ]
