# Generated by Django 2.2.12 on 2021-07-14 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0030_location_cover'),
        ('locations', '0029_location_cover'),
    ]

    operations = [
    ]
