# Generated by Django 2.2.12 on 2021-07-14 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0031_merge_20210714_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='cover',
            field=models.FileField(default='img/location/jay.jpg', upload_to='img/location'),
        ),
    ]
