# Generated by Django 3.2.4 on 2021-07-29 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0033_alter_location_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='cover',
            field=models.FileField(default='img/location/lalitpur.jpeg', upload_to='img/location/'),
        ),
    ]
